"""add jwst_requests table

Revision ID: 143a9e151eaf
Revises: 2b92cbb2c6bd
Create Date: 2026-10-05 09:35:54.538133

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '143a9e151eaf'
down_revision: Union[str, Sequence[str], None] = '2b92cbb2c6bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jwst_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('search_target', sa.String(), nullable=True),
    sa.Column('search_proposal_id', sa.String(), nullable=True),
    sa.Column('search_instrument', sa.String(), nullable=True),
    sa.Column('mast_product_uri', sa.String(), nullable=False),
    sa.Column('mast_obs_id', sa.String(), nullable=True),
    sa.Column('target_name', sa.String(), nullable=True),
    sa.Column('instrument_name', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'downloading', 'processing', 'completed', 'failed', name='jwst_request_status'), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('fits_path', sa.String(), nullable=True),
    sa.Column('preview_image_path', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_jwst_requests_id'), 'jwst_requests', ['id'], unique=False)
    op.create_index(op.f('ix_jwst_requests_mast_product_uri'), 'jwst_requests', ['mast_product_uri'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_jwst_requests_mast_product_uri'), table_name='jwst_requests')
    op.drop_index(op.f('ix_jwst_requests_id'), table_name='jwst_requests')
    op.drop_table('jwst_requests')
    # ### end Alembic commands ###
