"""initial full schema

Revision ID: 2b92cbb2c6bd
Revises: 
Create Date: 2026-09-26 18:25:55.067323

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2b92cbb2c6bd'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('astronomer_quotes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quote', sa.Text(), nullable=False),
    sa.Column('astronomer', sa.String(length=150), nullable=False),
    sa.Column('birth_year', sa.Integer(), nullable=True),
    sa.Column('death_year', sa.Integer(), nullable=True),
    sa.Column('nationality', sa.String(length=100), nullable=True),
    sa.Column('context', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=80), nullable=True),
    sa.Column('featured', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_astronomer_quotes_id'), 'astronomer_quotes', ['id'], unique=False)
    op.create_table('lessons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('difficulty', sa.String(), nullable=False),
    sa.Column('created_at', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lessons_id'), 'lessons', ['id'], unique=False)
    op.create_table('quiz_questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question_text', sa.String(), nullable=False),
    sa.Column('options', sa.Text(), nullable=False),
    sa.Column('correct_answer', sa.String(), nullable=False),
    sa.Column('difficulty', sa.String(), nullable=False),
    sa.Column('topic', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quiz_questions_id'), 'quiz_questions', ['id'], unique=False)
    op.create_table('solar_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('event_type', sa.String(length=80), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('peak_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('visible_regions', sa.Text(), nullable=True),
    sa.Column('min_latitude', sa.Float(), nullable=True),
    sa.Column('max_latitude', sa.Float(), nullable=True),
    sa.Column('zhr', sa.Integer(), nullable=True),
    sa.Column('radiant_ra', sa.Float(), nullable=True),
    sa.Column('radiant_dec', sa.Float(), nullable=True),
    sa.Column('parent_body', sa.String(length=100), nullable=True),
    sa.Column('eclipse_type', sa.String(length=50), nullable=True),
    sa.Column('magnitude', sa.Float(), nullable=True),
    sa.Column('source', sa.String(length=100), nullable=True),
    sa.Column('is_upcoming', sa.Boolean(), nullable=True),
    sa.Column('is_notable', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_solar_events_id'), 'solar_events', ['id'], unique=False)
    op.create_table('stars',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('catalog_id', sa.Integer(), nullable=False),
    sa.Column('proper_name', sa.String(), nullable=False),
    sa.Column('bayer_designation', sa.String(), nullable=True),
    sa.Column('constellation', sa.String(), nullable=False),
    sa.Column('iau_abbreviation', sa.String(), nullable=True),
    sa.Column('ra', sa.String(), nullable=False),
    sa.Column('dec', sa.String(), nullable=False),
    sa.Column('magnitude', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('catalog_id')
    )
    op.create_index('ix_star_constellation', 'stars', ['constellation'], unique=False)
    op.create_index('ix_star_proper_name', 'stars', ['proper_name'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('role', sa.Enum('admin', 'user', 'premium', name='userrole'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('location', sa.String(length=200), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('timezone', sa.String(length=80), nullable=True),
    sa.Column('language', sa.String(length=20), nullable=True),
    sa.Column('date_of_birth', sa.DateTime(), nullable=True),
    sa.Column('occupation', sa.String(length=150), nullable=True),
    sa.Column('astronomy_level', sa.String(length=50), nullable=True),
    sa.Column('x_handle', sa.String(length=100), nullable=True),
    sa.Column('instagram_handle', sa.String(length=100), nullable=True),
    sa.Column('website_url', sa.String(length=300), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('location_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('elevation', sa.Float(), nullable=True),
    sa.Column('country', sa.String(length=128), nullable=True),
    sa.Column('state', sa.String(length=128), nullable=True),
    sa.Column('city', sa.String(length=128), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_location_entries_id'), 'location_entries', ['id'], unique=False)
    op.create_table('quiz_submissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('total_questions', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quiz_submissions_id'), 'quiz_submissions', ['id'], unique=False)
    op.create_table('star_watchlist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('star_name', sa.String(), nullable=False),
    sa.Column('constellation', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('added_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_star_watchlist_id'), 'star_watchlist', ['id'], unique=False)
    op.create_table('transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.Enum('mpesa', 'paystack', name='paymentprovider'), nullable=False),
    sa.Column('status', sa.Enum('pending', 'completed', 'failed', 'refunded', 'cancelled', name='paymentstatus'), nullable=True),
    sa.Column('plan', sa.Enum('free', 'pro', 'premium', name='plantier'), nullable=False),
    sa.Column('interval', sa.Enum('monthly', 'yearly', name='planinterval'), nullable=True),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('mpesa_checkout_request_id', sa.String(length=100), nullable=True),
    sa.Column('mpesa_merchant_request_id', sa.String(length=100), nullable=True),
    sa.Column('mpesa_receipt_number', sa.String(length=50), nullable=True),
    sa.Column('mpesa_phone', sa.String(length=20), nullable=True),
    sa.Column('paystack_reference', sa.String(length=100), nullable=True),
    sa.Column('paystack_channel', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transactions_id'), 'transactions', ['id'], unique=False)
    op.create_index(op.f('ix_transactions_mpesa_checkout_request_id'), 'transactions', ['mpesa_checkout_request_id'], unique=False)
    op.create_index(op.f('ix_transactions_paystack_reference'), 'transactions', ['paystack_reference'], unique=False)
    op.create_table('user_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('dark_mode', sa.Boolean(), nullable=True),
    sa.Column('default_difficulty', sa.String(), nullable=True),
    sa.Column('notifications_enabled', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_settings_id'), 'user_settings', ['id'], unique=False)
    op.create_table('user_subscriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('plan', sa.Enum('free', 'pro', 'premium', name='plantier'), nullable=False),
    sa.Column('status', sa.Enum('active', 'cancelled', 'expired', 'trial', 'paused', name='subscriptionstatus'), nullable=True),
    sa.Column('interval', sa.Enum('monthly', 'yearly', name='planinterval'), nullable=True),
    sa.Column('provider', sa.Enum('mpesa', 'paystack', name='paymentprovider'), nullable=True),
    sa.Column('mpesa_phone', sa.String(length=20), nullable=True),
    sa.Column('paystack_customer_id', sa.String(length=100), nullable=True),
    sa.Column('paystack_reference', sa.String(length=100), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('current_period_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('current_period_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('trial_ends_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_user_subscriptions_id'), 'user_subscriptions', ['id'], unique=False)
    op.create_index(op.f('ix_user_subscriptions_paystack_customer_id'), 'user_subscriptions', ['paystack_customer_id'], unique=False)
    op.create_index(op.f('ix_user_subscriptions_paystack_reference'), 'user_subscriptions', ['paystack_reference'], unique=False)
    op.create_table('quiz_answers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('submission_id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('selected_answer', sa.String(), nullable=False),
    sa.Column('correct_answer', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['submission_id'], ['quiz_submissions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quiz_answers_id'), 'quiz_answers', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_quiz_answers_id'), table_name='quiz_answers')
    op.drop_table('quiz_answers')
    op.drop_index(op.f('ix_user_subscriptions_paystack_reference'), table_name='user_subscriptions')
    op.drop_index(op.f('ix_user_subscriptions_paystack_customer_id'), table_name='user_subscriptions')
    op.drop_index(op.f('ix_user_subscriptions_id'), table_name='user_subscriptions')
    op.drop_table('user_subscriptions')
    op.drop_index(op.f('ix_user_settings_id'), table_name='user_settings')
    op.drop_table('user_settings')
    op.drop_index(op.f('ix_transactions_paystack_reference'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_mpesa_checkout_request_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_id'), table_name='transactions')
    op.drop_table('transactions')
    op.drop_index(op.f('ix_star_watchlist_id'), table_name='star_watchlist')
    op.drop_table('star_watchlist')
    op.drop_index(op.f('ix_quiz_submissions_id'), table_name='quiz_submissions')
    op.drop_table('quiz_submissions')
    op.drop_index(op.f('ix_location_entries_id'), table_name='location_entries')
    op.drop_table('location_entries')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index('ix_star_proper_name', table_name='stars')
    op.drop_index('ix_star_constellation', table_name='stars')
    op.drop_table('stars')
    op.drop_index(op.f('ix_solar_events_id'), table_name='solar_events')
    op.drop_table('solar_events')
    op.drop_index(op.f('ix_quiz_questions_id'), table_name='quiz_questions')
    op.drop_table('quiz_questions')
    op.drop_index(op.f('ix_lessons_id'), table_name='lessons')
    op.drop_table('lessons')
    op.drop_index(op.f('ix_astronomer_quotes_id'), table_name='astronomer_quotes')
    op.drop_table('astronomer_quotes')
    # ### end Alembic commands ###
